import { SchoolType } from '@prisma/client';

export const DEFAULT_MODULES: Record<SchoolType, string[]> = {
    [SchoolType.SCHOOL]: [
        "ATTENDANCE", "EXAMS", "TIMETABLE", "LESSON_PLANNING", "SUBSTITUTIONS",
        "NOTICES", "GRIEVANCES", "CALENDAR", "ANNOUNCEMENTS", "ADMIN_MANAGEMENT",
        "DEPARTMENTS", "HOUSES", "FACILITY_MANAGEMENT", "TEACHERS", "STUDENTS",
        "CLASSES", "SUBJECTS", "LOGS", "SETTINGS", "LIBRARY", "MESSAGING",
        "HOMEWORK", "LEAVE_MANAGEMENT", "ACADEMICS", "ACTIVITIES", "NOTIFICATIONS",
        "SUBDOMAIN_LANDING_PAGE"
    ],
    [SchoolType.COLLEGE]: [
        "ATTENDANCE", "EXAMS", "TIMETABLE", "LESSON_PLANNING", "SUBSTITUTIONS",
        "NOTICES", "GRIEVANCES", "CALENDAR", "ANNOUNCEMENTS", "ADMIN_MANAGEMENT",
        "DEPARTMENTS", "HOUSES", "FACILITY_MANAGEMENT", "TEACHERS", "STUDENTS",
        "CLASSES", "SUBJECTS", "LOGS", "SETTINGS", "LIBRARY", "MESSAGING",
        "HOMEWORK", "LEAVE_MANAGEMENT", "ACADEMICS", "ACTIVITIES", "NOTIFICATIONS",
        "SUBDOMAIN_LANDING_PAGE"
    ],
    [SchoolType.COACHING]: [
        "ATTENDANCE", "EXAMS", "TIMETABLE", "NOTICES", "ANNOUNCEMENTS",
        "TEACHERS", "STUDENTS", "CLASSES", "SUBJECTS", "SETTINGS", "MESSAGING",
        "HOMEWORK", "NOTIFICATIONS",
        "SUBDOMAIN_LANDING_PAGE"
    ]
};
