export enum SchoolAdminPermission {
    MANAGE_TEACHERS = 'MANAGE_TEACHERS',
    MANAGE_STUDENTS = 'MANAGE_STUDENTS',
    MANAGE_ATTENDANCE = 'MANAGE_ATTENDANCE',
    VIEW_REPORTS = 'VIEW_REPORTS',
    MANAGE_SETTINGS = 'MANAGE_SETTINGS',
}
